### ISSUE TITLE
Solo или командное участие или и то и то?

### ISSUE THREAD

**Issue by MixailE** [bddays/jam#7]
При организации первого jam, можно не проводить четкого разделения  solo участников и команд. В будущем для честной оценки возможно предпочтем разделение или продумаем особую систему оценки.

**Comment by johnnykramer** [comment]
+ за общее понятие "команда", без разделения на одиночек и команды. и не на первый джем, а вообще.

**Comment by cra** [comment]
я за команды, без детализации и разделения.
На том же гитхабе нет отдельного рейтинга у проектов которые разработаывает только один человек

**Comment by nof1000** [comment]
Считаю, что нужно чётко разделять единичное на количественное; Команда может сделать за один и тот же отведённый срок, теоретически, больше. Либо делать как у LD: время для соло участников и для команд строиться отдельно; и по сути, делать (разделять) их друг от друга, но сравнивать в общем рейтинге. Можно, конечно, изначально соло участникам давать некий плюс в рейтинг, но это уже прямая мотивация участвовать в соло нежели в команде. Не то чтоб это всё слишком серьезный вопрос, но его нужно продумать чтобы в последующем не было всяческих конфузов.
